# Generated by Django 2.2.5 on 2019-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191023_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspeciality',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
