# Generated by Django 2.2.5 on 2019-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191026_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile_avatars'),
        ),
    ]
