# Generated by Django 2.2.5 on 2019-10-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20191028_1808'),
        ('users', '0005_auto_20191028_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='at_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_at_clinic', to='appointment.Clinic'),
        ),
    ]
