# Generated by Django 2.2.5 on 2019-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorprofile_at_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='ic_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
