# Generated by Django 2.2.5 on 2019-11-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191031_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='ic_number',
            new_name='id_number',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_nationality', to='users.Nationality'),
        ),
    ]
