# Generated by Django 2.2.5 on 2019-11-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191102_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='id_type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
