# Generated by Django 2.2.5 on 2019-10-23 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(max_length=50)),
                ('self_description', models.TextField()),
                ('preferred_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('operating_time_from', models.TimeField(null=True)),
                ('operating_time_to', models.TimeField(null=True)),
                ('address', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.TextField()),
                ('medications', models.TextField()),
                ('directives', models.TextField()),
                ('allergies_and_adverse_reactions', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointment.Appointment')),
            ],
        ),
    ]
