# Generated by Django 2.2.5 on 2019-10-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20191023_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
