# Generated by Django 2.2.5 on 2019-10-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_doctoratclinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoratclinic',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
