# Generated by Django 2.2.5 on 2019-10-25 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0005_auto_20191023_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_clinic', to='appointment.Clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_clinic', to='appointment.Clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
