# Generated by Django 2.2.5 on 2019-10-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20191025_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191825', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='self_description',
            field=models.TextField(null=True),
        ),
    ]
