# Generated by Django 2.2.5 on 2019-10-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191023_2019'),
        ('appointment', '0007_auto_20191025_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_speciality', to='users.DoctorSpeciality'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20195726', max_length=50),
        ),
    ]
