# Generated by Django 2.2.5 on 2019-10-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191026_1809'),
        ('appointment', '0009_auto_20191026_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='speciality',
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_appointment_speciality', to='users.DoctorSpeciality'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='intended_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_appointment_speciality', to='users.DoctorSpeciality'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20192826', max_length=50),
        ),
    ]
