# Generated by Django 2.2.5 on 2019-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20191026_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20193726', max_length=50),
        ),
    ]
