# Generated by Django 2.2.5 on 2019-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20191026_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20190528', max_length=50),
        ),
        migrations.DeleteModel(
            name='DoctorAtClinic',
        ),
    ]
