# Generated by Django 2.2.5 on 2019-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20191028_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20190828', max_length=50),
        ),
    ]
