# Generated by Django 2.2.5 on 2019-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20191028_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191728', max_length=50),
        ),
        migrations.DeleteModel(
            name='DoctorAtClinic',
        ),
    ]
