# Generated by Django 2.2.5 on 2019-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20191028_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='display',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20192128', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
