# Generated by Django 2.2.5 on 2019-10-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_auto_20191029_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20190530', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies_and_adverse_reactions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointment.Appointment'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='directives',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='problems',
            field=models.TextField(null=True),
        ),
    ]
