# Generated by Django 2.2.5 on 2019-10-31 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_auto_20191030_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191031132243', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_updated_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
