# Generated by Django 2.2.5 on 2019-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20191031_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191031132544', max_length=50),
        ),
    ]
