# Generated by Django 2.2.5 on 2019-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_auto_20191102_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191102165128', max_length=50),
        ),
    ]
