# Generated by Django 2.2.5 on 2019-11-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0025_auto_20191104_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.PositiveSmallIntegerField(default=8)),
                ('can_patient_view_med_records', models.BooleanField(default=False)),
                ('scope', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteDefaultSetting',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191104104408', max_length=50),
        ),
    ]
