# Generated by Django 2.2.5 on 2019-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0026_auto_20191104_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='can_patient_view_med_records',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(default='INDEX20191104132350', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='scope',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
