# Generated by Django 2.2.5 on 2019-11-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0030_auto_20191104_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(max_length=50),
        ),
    ]
