# Generated by Django 2.2.5 on 2019-11-05 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191102_1615'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0032_auto_20191105_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='speciality',
        ),
        migrations.AddField(
            model_name='appointment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='intended_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_appointment_speciality', to='users.DoctorSpeciality'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_updated_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_clinic', to='appointment.Clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
