# Generated by Django 2.2.5 on 2019-11-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0033_auto_20191105_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='actual_clinic',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='actual_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='actual_doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='actual_speciality',
        ),
    ]
