# Generated by Django 2.2.5 on 2019-11-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191102_1615'),
        ('appointment', '0034_auto_20191105_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='intended_speciality',
        ),
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_speciality', to='users.DoctorSpeciality'),
        ),
    ]
