# Generated by Django 2.2.5 on 2019-11-05 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0035_auto_20191105_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
