# Generated by Django 2.2.5 on 2019-11-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0036_auto_20191105_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_clinic',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_clinic', to='appointment.Clinic'),
        ),
    ]
