# Generated by Django 2.2.5 on 2019-11-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0037_auto_20191105_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='preferred_datetime',
            new_name='appointment_datetime',
        ),
    ]
