# Generated by Django 2.2.5 on 2019-11-09 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0039_auto_20191109_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='last_updated_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
