# Generated by Django 2.2.5 on 2019-11-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0040_auto_20191109_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
