# Generated by Django 2.2.5 on 2019-11-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0043_auto_20191111_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='schedule_per_page',
            new_name='doc_schedules_per_page',
        ),
    ]
