# Generated by Django 2.2.5 on 2019-11-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0044_auto_20191111_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('data_protection_policy', models.TextField(null=True)),
            ],
        ),
    ]
