# Generated by Django 2.2.5 on 2019-11-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0045_largecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='largecontext',
            name='scope',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='largecontext',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='largecontext',
            name='data_protection_policy',
            field=models.TextField(default='', null=True),
        ),
    ]
