# Generated by Django 2.2.5 on 2019-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0046_auto_20191115_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
