# Generated by Django 2.2.5 on 2019-11-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0047_auto_20191116_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LargeContext',
        ),
    ]
