# Generated by Django 2.2.5 on 2019-11-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0050_auto_20191119_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='actual_doctor',
            new_name='doctor',
        ),
    ]
