# Generated by Django 2.2.5 on 2019-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0053_auto_20191119_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(null=True)),
            ],
        ),
    ]
