# Generated by Django 2.2.5 on 2019-11-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0054_largecontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LargeContext',
        ),
    ]
