# Generated by Django 2.2.5 on 2019-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0056_auto_20191124_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='contact_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
