from django.urls import path
from django.conf.urls import handler404
from django.contrib.flatpages import views as flat_views
from django_filters.views import FilterView
from . import views
from .views import (AptmtDetailView,
                    AptmtCreateView,
                    AptmtUpdateByUserView,
                    AptmtDeleteView,
                    MyAptmtListView,
                    AptmtCancelByUserView,
                    AllAptmtListView,
                    AptmtUpdateByAdminView,
                    MedRecordUpdateByDoctorView,
                    DoctorAptmtListView,
                    ClinicListView,
                    DoctorListView,
                    DoctorDetailView,
                    AptmtCompeteByDoctorView,
                    SiteSettingUpdateView,
                    AllDoctorScheduleListView,
                    DocScheduleCreateByAdminView,
                    DocScheduleUpdateByAdminView,
                    MyScheduleListView,
                    DocScheduleCreateByDoctorView,
                    DocScheduleUpdateByDoctorView,
                    DocScheduleDeleteView,
                    FlatTextPageUpdateView,
                    ClinicUpdateView,
                    ClinicCreateView,
                    ClinicDeleteView,
                    ClinicDetailView,
                    AllAptmtCalendarView,
                    MyAptmtCalendarView,
                    DoctorAptmtCalendarView,
                  )

urlpatterns = [
    path('', views.home, name='home'),
    path('site-settings/<int:scope>/', SiteSettingUpdateView.as_view(), name='site-settings'),
    path('appointment/all/', AllAptmtListView.as_view(), name='aptmts-all'),
    path('appointment/all/calendar/', AllAptmtCalendarView.as_view(), name='aptmts-all-calendar'),
    path('appointment/my-appointments/', MyAptmtListView.as_view(), name='my-aptmts'),
    path('appointment/my-appointments/calendar/', MyAptmtCalendarView.as_view(), name='my-aptmts-calendar'),
    path('appointment/doc-appointments/', DoctorAptmtListView.as_view(), name='doc-aptmts'),
    path('appointment/doc-appointments/calendar/', DoctorAptmtCalendarView.as_view(), name='doc-aptmts-calendar'),
    path('appointment/<int:pk>/', AptmtDetailView.as_view(), name='aptmt-detail'),
    path('appointment/<int:pk>/delete/', AptmtDeleteView.as_view(), name='aptmt-delete'),
    path('appointment/<int:pk>/cancel-by-user/', AptmtCancelByUserView.as_view(), name='aptmt-cancel-by-user'),
    path('appointment/<int:pk>/complete/', AptmtCompeteByDoctorView.as_view(), name='aptmt-complete-by-doctor'),
    path('appointment/new/', AptmtCreateView.as_view(), name='aptmt-create'),
    path('appointment/check-profile-completeness/', views.check_profile_complete, name='check-profile-completeness'),
    path('appointment/<int:pk>/update/', AptmtUpdateByUserView.as_view(), name='aptmt-update-by-user'),
    path('appointment/<int:pk>/update-by-admin/', AptmtUpdateByAdminView.as_view(), name='aptmt-update-by-admin'),
    path('appointment/<int:appointment_id>/update-by-doctor/', MedRecordUpdateByDoctorView.as_view(),
         name='med-record-update-by-doctor'),
    # path('doctor-schedule/all/', AllDoctorScheduleListView.as_view(), name='doc-schedules-all'),
    # path('doctor-schedule/new/', DocScheduleCreateByAdminView.as_view(), name='doc-schedule-create-by-admin'),
    # path('doctor-schedule/<int:pk>/update/', DocScheduleUpdateByAdminView.as_view(),
    #      name='doc-schedule-update-by-admin'),
    # path('doctor-schedule/my/', MyScheduleListView.as_view(), name='my-schedule'),
    # path('doctor-schedule/my/new/', DocScheduleCreateByDoctorView.as_view(),
    #      name='doc-schedule-create-by-doctor'),
    # path('doctor-schedule/my/<int:pk>/update/', DocScheduleUpdateByDoctorView.as_view(),
    #      name='doc-schedule-update-by-doctor'),
    # path('doctor-schedule/<int:pk>/delete/', DocScheduleDeleteView.as_view(), name='doc-schedule-delete'),
    path('clinic/<int:pk>/update/', ClinicUpdateView.as_view(), name='clinic-update'),
    path('clinic/create/', ClinicCreateView.as_view(), name='clinic-create'),
    path('clinic/<int:pk>/delete/', ClinicDeleteView.as_view(), name='clinic-delete'),
    path('clinic-info/<int:pk>/', ClinicDetailView.as_view(), name='clinic-detail'),
    path('about/', flat_views.flatpage, {'url': '/about/'}, name='about'),
    path('contact-us/', flat_views.flatpage, {'url': '/contact-us/'}, name='contact-us'),
    path('terms-of-services/', flat_views.flatpage, {'url': '/terms-of-services/'}, name='terms-of-services'),
    path('privacy-policy/', flat_views.flatpage, {'url': '/privacy-policy/'}, name='privacy-policy'),
    path('flat-text-page/<int:pk>/update/', FlatTextPageUpdateView.as_view(), {'url': '/about-us/'},
         name='flat-text-page-update'),
    path('clinics/', ClinicListView.as_view(), name='clinics'),
    path('doctors/', DoctorListView.as_view(), name='doctors'),
    path('doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor-detail'),
    path('ajax/load-clinics/', views.load_clinics, name='ajax-load-clinics'),
]

# handler404 = views.error_404_view
